name: ci

on:
  push:
  pull_request:

jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Install Task
        run: go install github.com/go-task/task/v3/cmd/task@latest

      - name: Build
        run: task build

      - name: Test
        run: task test:cover

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: justskiv/gatekeeper
          files: ./coverage.out

      - name: Lint
        run: task lint
